// GENERATED by web/tools/build_pages.py from web/site.json. Do not edit.
export const SITE = {
  "name": "NightCal",
  "place": "Downtown Santa Rosa",
  "tagline": "What's on downtown tonight, from listings that cite their source.",
  "origin": "https://nightcal.justadestination.com",
  "zineName": "AVR+JIT",
  "twitter": "",
  "locale": "en_US"
};
export default SITE;
