// NightCal tokens. GENERATED by tokens/build.py from tokens/*.json. Do not edit.
// Used by the theme API (contrast checks on overrides) and by the 3D renderer.
export const TOKENS = {
  "prefix": "--nc-",
  "themes": {
    "light": {
      "label": "Light",
      "colorScheme": "light",
      "values": {
        "color-bg": "#F6F4EE",
        "color-surface": "#FFFFFF",
        "color-surface-raised": "#FFFFFF",
        "color-surface-sunken": "#ECE9E1",
        "color-text": "#121214",
        "color-text-muted": "#57534A",
        "color-border": "#DAD5C9",
        "color-border-strong": "#6E695D",
        "color-accent": "#FFC14D",
        "color-on-accent": "#121214",
        "color-accent-text": "#8A4B00",
        "color-link": "#0842A0",
        "color-focus": "#0B57D0",
        "color-selected-bg": "#121214",
        "color-selected-text": "#FFFFFF",
        "color-today": "#8A4B00",
        "color-scrim": "rgba(18, 18, 20, 0.55)",
        "color-shadow": "rgba(18, 18, 20, 0.12)",
        "color-kind-music-bg": "#DCF2E3",
        "color-kind-music-fg": "#0B5A2A",
        "color-kind-music-mark": "#1E7A43",
        "color-kind-comedy-bg": "#FDE3DE",
        "color-kind-comedy-fg": "#8A1F12",
        "color-kind-comedy-mark": "#C2402B",
        "color-kind-show-bg": "#DDE8FB",
        "color-kind-show-fg": "#123E86",
        "color-kind-show-mark": "#2F67C8",
        "color-kind-trivia-bg": "#ECE2FA",
        "color-kind-trivia-fg": "#4D2386",
        "color-kind-trivia-mark": "#7A47BE",
        "color-kind-food-bg": "#FFF0CC",
        "color-kind-food-fg": "#6B4A00",
        "color-kind-food-mark": "#946A00",
        "color-kind-other-bg": "#ECEAE4",
        "color-kind-other-fg": "#3F3B33",
        "color-kind-other-mark": "#6F6A5E",
        "color-graph-edge": "#817B6D",
        "color-graph-edge-active": "#121214",
        "color-node-article": "#2F67C8",
        "color-node-review": "#C2402B",
        "color-node-letter": "#7A47BE",
        "color-node-editorial": "#6F6A5E",
        "color-node-event": "#1E7A43",
        "color-node-venue": "#946A00",
        "color-node-entity": "#57534A",
        "color-node-missing": "#817B6D",
        "shadow-raised": "0 1px 2px rgba(18, 18, 20, 0.08), 0 2px 8px rgba(18, 18, 20, 0.06)",
        "shadow-overlay": "0 12px 40px rgba(18, 18, 20, 0.22)"
      },
      "refs": {
        "color-bg": "palette-neutral-50",
        "color-surface": "palette-neutral-0",
        "color-surface-raised": "palette-neutral-0",
        "color-surface-sunken": "palette-neutral-100",
        "color-text": "palette-neutral-950",
        "color-text-muted": "palette-neutral-600",
        "color-border": "palette-neutral-200",
        "color-border-strong": "palette-neutral-500",
        "color-accent": "palette-amber-400",
        "color-on-accent": "palette-neutral-950",
        "color-accent-text": "palette-amber-700",
        "color-link": "palette-blue-700",
        "color-focus": "palette-blue-600",
        "color-selected-bg": "palette-neutral-950",
        "color-selected-text": "palette-neutral-0",
        "color-today": "palette-amber-700",
        "color-kind-music-bg": "palette-green-100",
        "color-kind-music-fg": "palette-green-800",
        "color-kind-music-mark": "palette-green-700",
        "color-kind-comedy-bg": "palette-coral-100",
        "color-kind-comedy-fg": "palette-coral-800",
        "color-kind-comedy-mark": "palette-coral-700",
        "color-kind-show-bg": "palette-azure-100",
        "color-kind-show-fg": "palette-azure-800",
        "color-kind-show-mark": "palette-azure-700",
        "color-kind-trivia-bg": "palette-violet-100",
        "color-kind-trivia-fg": "palette-violet-800",
        "color-kind-trivia-mark": "palette-violet-700",
        "color-kind-food-bg": "palette-gold-100",
        "color-kind-food-fg": "palette-gold-800",
        "color-kind-food-mark": "palette-gold-700",
        "color-kind-other-bg": "palette-stone-100",
        "color-kind-other-fg": "palette-stone-800",
        "color-kind-other-mark": "palette-stone-700",
        "color-graph-edge": "palette-neutral-400",
        "color-graph-edge-active": "palette-neutral-950",
        "color-node-article": "palette-azure-700",
        "color-node-review": "palette-coral-700",
        "color-node-letter": "palette-violet-700",
        "color-node-editorial": "palette-stone-700",
        "color-node-event": "palette-green-700",
        "color-node-venue": "palette-gold-700",
        "color-node-entity": "palette-neutral-600",
        "color-node-missing": "palette-neutral-400"
      }
    },
    "dark": {
      "label": "Dark",
      "colorScheme": "dark",
      "values": {
        "color-bg": "#121214",
        "color-surface": "#1A1A1E",
        "color-surface-raised": "#222226",
        "color-surface-sunken": "#0B0B0C",
        "color-text": "#F4F1EA",
        "color-text-muted": "#B8B3A8",
        "color-border": "#2A2825",
        "color-border-strong": "#85817A",
        "color-accent": "#FFC14D",
        "color-on-accent": "#121214",
        "color-accent-text": "#FFD27A",
        "color-link": "#A8C7FA",
        "color-focus": "#A8C7FA",
        "color-selected-bg": "#FFC14D",
        "color-selected-text": "#121214",
        "color-today": "#FFC14D",
        "color-scrim": "rgba(0, 0, 0, 0.7)",
        "color-shadow": "rgba(0, 0, 0, 0.5)",
        "color-kind-music-bg": "#123321",
        "color-kind-music-fg": "#9FE5B8",
        "color-kind-music-mark": "#3FB56C",
        "color-kind-comedy-bg": "#3A1712",
        "color-kind-comedy-fg": "#FFB4A6",
        "color-kind-comedy-mark": "#F26B55",
        "color-kind-show-bg": "#132544",
        "color-kind-show-fg": "#A9C8FF",
        "color-kind-show-mark": "#6FA0F5",
        "color-kind-trivia-bg": "#2A1C40",
        "color-kind-trivia-fg": "#D4BCFF",
        "color-kind-trivia-mark": "#B08CF0",
        "color-kind-food-bg": "#33280F",
        "color-kind-food-fg": "#FFD98A",
        "color-kind-food-mark": "#D9A630",
        "color-kind-other-bg": "#28272B",
        "color-kind-other-fg": "#D5D1C8",
        "color-kind-other-mark": "#9C978C",
        "color-graph-edge": "#6A665F",
        "color-graph-edge-active": "#F4F1EA",
        "color-node-article": "#6FA0F5",
        "color-node-review": "#F26B55",
        "color-node-letter": "#B08CF0",
        "color-node-editorial": "#9C978C",
        "color-node-event": "#3FB56C",
        "color-node-venue": "#D9A630",
        "color-node-entity": "#A9A49A",
        "color-node-missing": "#77736C",
        "shadow-raised": "0 1px 2px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.04)",
        "shadow-overlay": "0 16px 48px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(255, 255, 255, 0.06)"
      },
      "refs": {
        "color-bg": "palette-neutral-950",
        "color-surface": "palette-neutral-900",
        "color-surface-raised": "palette-neutral-850",
        "color-surface-sunken": "palette-neutral-1000",
        "color-border": "palette-neutral-800",
        "color-accent": "palette-amber-400",
        "color-on-accent": "palette-neutral-950",
        "color-accent-text": "palette-amber-300",
        "color-link": "palette-blue-300",
        "color-focus": "palette-blue-300",
        "color-selected-bg": "palette-amber-400",
        "color-selected-text": "palette-neutral-950",
        "color-today": "palette-amber-400",
        "color-kind-music-bg": "palette-green-900",
        "color-kind-music-fg": "palette-green-300",
        "color-kind-music-mark": "palette-green-500",
        "color-kind-comedy-bg": "palette-coral-900",
        "color-kind-comedy-fg": "palette-coral-300",
        "color-kind-comedy-mark": "palette-coral-500",
        "color-kind-show-bg": "palette-azure-900",
        "color-kind-show-fg": "palette-azure-300",
        "color-kind-show-mark": "palette-azure-500",
        "color-kind-trivia-bg": "palette-violet-900",
        "color-kind-trivia-fg": "palette-violet-300",
        "color-kind-trivia-mark": "palette-violet-500",
        "color-kind-food-bg": "palette-gold-900",
        "color-kind-food-fg": "palette-gold-300",
        "color-kind-food-mark": "palette-gold-500",
        "color-kind-other-bg": "palette-stone-900",
        "color-kind-other-fg": "palette-stone-300",
        "color-kind-other-mark": "palette-stone-500",
        "color-node-article": "palette-azure-500",
        "color-node-review": "palette-coral-500",
        "color-node-letter": "palette-violet-500",
        "color-node-editorial": "palette-stone-500",
        "color-node-event": "palette-green-500",
        "color-node-venue": "palette-gold-500"
      }
    }
  },
  "primitives": {
    "palette-neutral-0": "#FFFFFF",
    "palette-neutral-25": "#FBFAF7",
    "palette-neutral-50": "#F6F4EE",
    "palette-neutral-100": "#ECE9E1",
    "palette-neutral-200": "#DAD5C9",
    "palette-neutral-300": "#BDB7A9",
    "palette-neutral-400": "#817B6D",
    "palette-neutral-500": "#6E695D",
    "palette-neutral-600": "#57534A",
    "palette-neutral-700": "#3E3B35",
    "palette-neutral-800": "#2A2825",
    "palette-neutral-850": "#222226",
    "palette-neutral-900": "#1A1A1E",
    "palette-neutral-950": "#121214",
    "palette-neutral-1000": "#0B0B0C",
    "palette-amber-100": "#FFF1D1",
    "palette-amber-300": "#FFD27A",
    "palette-amber-400": "#FFC14D",
    "palette-amber-500": "#F0A619",
    "palette-amber-700": "#8A4B00",
    "palette-amber-800": "#6B3A00",
    "palette-blue-300": "#A8C7FA",
    "palette-blue-600": "#0B57D0",
    "palette-blue-700": "#0842A0",
    "palette-green-100": "#DCF2E3",
    "palette-green-300": "#9FE5B8",
    "palette-green-500": "#3FB56C",
    "palette-green-700": "#1E7A43",
    "palette-green-800": "#0B5A2A",
    "palette-green-900": "#123321",
    "palette-coral-100": "#FDE3DE",
    "palette-coral-300": "#FFB4A6",
    "palette-coral-500": "#F26B55",
    "palette-coral-700": "#C2402B",
    "palette-coral-800": "#8A1F12",
    "palette-coral-900": "#3A1712",
    "palette-azure-100": "#DDE8FB",
    "palette-azure-300": "#A9C8FF",
    "palette-azure-500": "#6FA0F5",
    "palette-azure-700": "#2F67C8",
    "palette-azure-800": "#123E86",
    "palette-azure-900": "#132544",
    "palette-violet-100": "#ECE2FA",
    "palette-violet-300": "#D4BCFF",
    "palette-violet-500": "#B08CF0",
    "palette-violet-700": "#7A47BE",
    "palette-violet-800": "#4D2386",
    "palette-violet-900": "#2A1C40",
    "palette-gold-100": "#FFF0CC",
    "palette-gold-300": "#FFD98A",
    "palette-gold-500": "#D9A630",
    "palette-gold-700": "#946A00",
    "palette-gold-800": "#6B4A00",
    "palette-gold-900": "#33280F",
    "palette-stone-100": "#ECEAE4",
    "palette-stone-300": "#D5D1C8",
    "palette-stone-500": "#9C978C",
    "palette-stone-700": "#6F6A5E",
    "palette-stone-800": "#3F3B33",
    "palette-stone-900": "#28272B",
    "font-family-sans": "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-family-display": "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-family-mono": "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, Consolas, \"Liberation Mono\", monospace",
    "font-size-xs": "0.8125rem",
    "font-size-sm": "0.875rem",
    "font-size-md": "1rem",
    "font-size-lg": "1.25rem",
    "font-size-xl": "1.5rem",
    "font-size-2xl": "2rem",
    "font-size-3xl": "2.75rem",
    "font-size-display": "clamp(2.25rem, 1.5rem + 3.5vw, 4rem)",
    "font-weight-regular": "400",
    "font-weight-medium": "500",
    "font-weight-bold": "700",
    "font-weight-heavy": "800",
    "font-line-height-tight": "1.1",
    "font-line-height-snug": "1.3",
    "font-line-height-normal": "1.5",
    "font-tracking-tight": "-0.02em",
    "font-tracking-normal": "0",
    "font-tracking-caps": "0.06em",
    "space-0": "0",
    "space-1": "calc(0.25rem * var(--nc-density))",
    "space-2": "calc(0.5rem * var(--nc-density))",
    "space-3": "calc(0.75rem * var(--nc-density))",
    "space-4": "calc(1rem * var(--nc-density))",
    "space-5": "calc(1.5rem * var(--nc-density))",
    "space-6": "calc(2rem * var(--nc-density))",
    "space-7": "calc(3rem * var(--nc-density))",
    "space-8": "calc(4rem * var(--nc-density))",
    "radius-sm": "6px",
    "radius-md": "10px",
    "radius-lg": "16px",
    "radius-pill": "999px",
    "size-target": "2.75rem",
    "size-focus-ring": "3px",
    "size-focus-offset": "2px",
    "size-border": "1px",
    "size-border-strong": "2px",
    "size-content-max": "72rem",
    "size-measure": "65ch",
    "size-gutter": "1rem",
    "size-glyph": "0.75rem",
    "size-dash": "6px",
    "size-gap": "4px",
    "duration-fast": "calc(120ms * var(--nc-motion-scale))",
    "duration-base": "calc(200ms * var(--nc-motion-scale))",
    "duration-slow": "calc(320ms * var(--nc-motion-scale))",
    "easing-standard": "cubic-bezier(0.2, 0, 0, 1)",
    "easing-exit": "cubic-bezier(0.3, 0, 1, 1)",
    "density-compact": "0.8",
    "density-comfortable": "1",
    "density-spacious": "1.25",
    "z-base": "0",
    "z-raised": "10",
    "z-overlay": "100",
    "z-toast": "200"
  },
  "density": {
    "compact": 0.8,
    "comfortable": 1,
    "spacious": 1.25
  },
  "knobs": {
    "text-scale": "1",
    "density": "1",
    "motion-scale": "1"
  },
  "pairs": [
    {
      "fg": "text",
      "bg": "bg",
      "min": 4.5
    },
    {
      "fg": "text",
      "bg": "surface",
      "min": 4.5
    },
    {
      "fg": "text",
      "bg": "surface-raised",
      "min": 4.5
    },
    {
      "fg": "text",
      "bg": "surface-sunken",
      "min": 4.5
    },
    {
      "fg": "text-muted",
      "bg": "bg",
      "min": 4.5
    },
    {
      "fg": "text-muted",
      "bg": "surface",
      "min": 4.5
    },
    {
      "fg": "text-muted",
      "bg": "surface-raised",
      "min": 4.5
    },
    {
      "fg": "text-muted",
      "bg": "surface-sunken",
      "min": 4.5
    },
    {
      "fg": "accent-text",
      "bg": "bg",
      "min": 4.5
    },
    {
      "fg": "accent-text",
      "bg": "surface",
      "min": 4.5
    },
    {
      "fg": "link",
      "bg": "bg",
      "min": 4.5
    },
    {
      "fg": "link",
      "bg": "surface",
      "min": 4.5
    },
    {
      "fg": "link",
      "bg": "surface-raised",
      "min": 4.5
    },
    {
      "fg": "on-accent",
      "bg": "accent",
      "min": 4.5
    },
    {
      "fg": "selected-text",
      "bg": "selected-bg",
      "min": 4.5
    },
    {
      "fg": "border-strong",
      "bg": "bg",
      "min": 3
    },
    {
      "fg": "border-strong",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "focus",
      "bg": "bg",
      "min": 3
    },
    {
      "fg": "focus",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "focus",
      "bg": "surface-raised",
      "min": 3
    },
    {
      "fg": "today",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "today",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "accent",
      "bg": "bg",
      "min": 1.0
    },
    {
      "fg": "kind-music-fg",
      "bg": "kind-music-bg",
      "min": 4.5
    },
    {
      "fg": "kind-comedy-fg",
      "bg": "kind-comedy-bg",
      "min": 4.5
    },
    {
      "fg": "kind-show-fg",
      "bg": "kind-show-bg",
      "min": 4.5
    },
    {
      "fg": "kind-trivia-fg",
      "bg": "kind-trivia-bg",
      "min": 4.5
    },
    {
      "fg": "kind-food-fg",
      "bg": "kind-food-bg",
      "min": 4.5
    },
    {
      "fg": "kind-other-fg",
      "bg": "kind-other-bg",
      "min": 4.5
    },
    {
      "fg": "kind-music-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-comedy-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-show-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-trivia-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-food-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-other-mark",
      "bg": "surface",
      "min": 3
    },
    {
      "fg": "kind-music-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "kind-comedy-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "kind-show-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "kind-trivia-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "kind-food-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "kind-other-mark",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-article",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-review",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-letter",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-editorial",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-event",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-venue",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-entity",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "node-missing",
      "bg": "surface-sunken",
      "min": 3
    },
    {
      "fg": "graph-edge",
      "bg": "surface-sunken",
      "min": 3
    }
  ]
};
export default TOKENS;
