#!/usr/bin/env python3
"""Write every static HTML route, the CSS bundle and the site module.

    python3 web/tools/build_pages.py

Inputs
    web/site.json                 site identity (name, place, origin)
    web/routes.json               full pages
    web/components/<name>/        one embed route per component folder that has <name>.js
    web/css/tokens.css, base.css  plus every components/*/*.css -> css/nightcal.css
    web/js/core/theme-boot.js     inlined in <head> so themes never flash

Outputs (generated, committed so any static host can serve web/ as-is)
    web/<path>/index.html         pages
    web/embed/<name>/index.html   embeds
    web/css/nightcal.css          single stylesheet
    web/js/core/site.js           SITE constants for the runtime
    web/components/index.json     component registry for the gallery
    web/sitemap.xml, web/robots.txt
"""

from __future__ import annotations

import base64
import hashlib
import html
import json
import re
from pathlib import Path

WEB = Path(__file__).resolve().parent.parent
ROOT = WEB.parent
SITE = json.loads((WEB / "site.json").read_text())
ROUTES = json.loads((WEB / "routes.json").read_text())
TOKENS = json.loads((ROOT / "tokens" / "dist" / "tokens.json").read_text())
CSS_ORDER = ["kind-tag", "button"]  # primitives first; the rest alphabetical
OG_W, OG_H = 1200, 630


STATIC_IMPORT = re.compile(r'^\s*(?:import|export)\s[^;]*?from\s+"([^"]+)"|^\s*import\s+"([^"]+)"', re.M)


def module_graph(module: str) -> list[str]:
    """Every module a page imports statically, so all can be preloaded in parallel
    instead of discovered one round-trip at a time. Dynamic import() stays lazy."""
    seen: list[str] = []
    stack = [module]
    while stack:
        rel = stack.pop()
        if rel in seen:
            continue
        seen.append(rel)
        path = WEB / rel
        if not path.exists():
            continue
        for m in STATIC_IMPORT.finditer(path.read_text()):
            spec = m.group(1) or m.group(2)
            if spec.startswith("."):
                stack.append(str((path.parent / spec).resolve().relative_to(WEB)))
    return seen


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def sha256(text: str) -> str:
    return "sha256-" + base64.b64encode(hashlib.sha256(text.encode()).digest()).decode()


def component_meta(path: Path) -> dict | None:
    src = path.read_text()
    block = re.search(r"export const meta = \{(.*?)\n\};", src, re.S)
    if not block:
        return None
    body = block.group(1)

    def field(name: str) -> str:
        m = re.search(rf'\b{name}: "((?:[^"\\]|\\.)*)"', body)
        return json.loads(f'"{m.group(1)}"') if m else ""

    params = {}
    pm = re.search(r"params: \{(.*?)\}", body, re.S)
    if pm:
        for key, value in re.findall(r'(\w+): (?:"((?:[^"\\]|\\.)*)"|[^,}]+)', pm.group(1)):
            params[key] = json.loads(f'"{value}"') if value else "see source"
    return {"name": field("name"), "title": field("title"), "summary": field("summary"), "params": params}


def components() -> list[dict]:
    out = []
    for folder in sorted((WEB / "components").iterdir()):
        js = folder / f"{folder.name}.js"
        if folder.is_dir() and js.exists():
            meta = component_meta(js)
            if meta and meta["name"] == folder.name:
                meta["readme"] = (folder / "README.md").exists()
                out.append(meta)
    return out


def bundle_css() -> str:
    parts = [(WEB / "css" / name).read_text() for name in ("tokens.css", "base.css", "pages.css")]
    folders = sorted((WEB / "components").iterdir(), key=lambda p: (CSS_ORDER.index(p.name) if p.name in CSS_ORDER else len(CSS_ORDER), p.name))
    for folder in folders:
        css = folder / f"{folder.name}.css"
        if css.exists():
            parts.append(f"/* --- components/{folder.name} --- */\n" + css.read_text())
    text = "/* NightCal stylesheet. GENERATED by web/tools/build_pages.py. Edit tokens/, css/ or the per-component CSS files. */\n" + "\n".join(parts)
    (WEB / "css" / "nightcal.css").write_text(text)
    return hashlib.sha256(text.encode()).hexdigest()[:10]


def boot_script() -> str:
    src = (WEB / "js" / "core" / "theme-boot.js").read_text()
    lines = [ln for ln in src.splitlines() if not ln.strip().startswith("//")]
    return "\n".join(lines).strip()


SHELLS = {
    # Static first paint for the two main pages: real headings, so the largest
    # contentful paint happens before any script or data arrives.
    "calendar": lambda: f"""<main id="main" class="nc-container nc-page nc-shell" tabindex="-1">
  <p class="nc-eyebrow">{esc(SITE['place'])}</p>
  <h1 class="nc-h1">What's on tonight</h1>
  <p class="nc-lede">Loading tonight's listings…</p>
</main>""",
    "zine": lambda: f"""<main id="main" class="nc-container nc-page nc-shell" tabindex="-1">
  <p class="nc-eyebrow">The {esc(SITE['zineName'])} zine</p>
  <h1 class="nc-h1">The zine, as a map</h1>
  <p class="nc-lede">Loading the map…</p>
</main>""",
}


def page(*, path: str, title: str, description: str, module: str, og: str, body_class: str = "",
         body_attrs: str = "", shell: str = "", css_hash: str, boot: str, embed: bool = False,
         importmap: str = "", also: str = "") -> str:
    url = SITE["origin"].rstrip("/") + path
    image = f"{SITE['origin'].rstrip('/')}/og/{og}.png"
    light_bg = TOKENS["light"]["--nc-color-bg"]
    dark_bg = TOKENS["dark"]["--nc-color-bg"]
    if light_bg.startswith("var("):
        light_bg = TOKENS["light"][light_bg[4:-1]]
    if dark_bg.startswith("var("):
        dark_bg = TOKENS["dark"][dark_bg[4:-1]]
    scripts = [boot] + ([importmap] if importmap else [])
    csp = "; ".join([
        "default-src 'self'",
        "script-src 'self' " + " ".join(f"'{sha256(s)}'" for s in scripts),
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' https: data: blob:",
        "connect-src 'self'",
        "frame-src 'self'",
        "base-uri 'self'",
        "form-action 'self'",
    ])
    skip = "" if embed else '<a class="nc-skip" href="#main">Skip to content</a>\n'
    content = SHELLS[shell]() if shell in SHELLS else ""
    noscript = "<noscript><p class=\"nc-container nc-section\">NightCal needs JavaScript turned on to show listings.</p></noscript>"
    im = f'<script type="importmap">{importmap}</script>\n' if importmap else ""
    preloads = "".join(f'<link rel="modulepreload" href="/{m}">\n' for m in dict.fromkeys(module_graph(module) + (module_graph(also) if also else [])))
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta http-equiv="Content-Security-Policy" content="{esc(csp)}">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{esc(url)}">
<meta name="color-scheme" content="light dark">
<meta name="theme-color" media="(prefers-color-scheme: light)" content="{light_bg}">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="{dark_bg}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="{esc(SITE['name'])}">
<meta property="og:locale" content="{esc(SITE.get('locale', 'en_US'))}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{esc(url)}">
<meta property="og:image" content="{esc(image)}">
<meta property="og:image:width" content="{OG_W}">
<meta property="og:image:height" content="{OG_H}">
<meta property="og:image:alt" content="{esc(title)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(description)}">
<meta name="twitter:image" content="{esc(image)}">
<meta name="twitter:image:alt" content="{esc(title)}">
{f'<meta name="twitter:site" content="{esc(SITE["twitter"])}">' + chr(10) if SITE.get("twitter") else ""}<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<script>{boot}</script>
<link rel="stylesheet" href="/css/nightcal.css?v={css_hash}">
{im}{preloads}
<script type="module" src="/{module}"></script>
</head>
<body{f' class="{body_class}"' if body_class else ""}{body_attrs}>
{skip}<div id="app">{content}</div>
{noscript}
</body>
</html>
"""


def write(path: str, text: str) -> None:
    target = WEB / path.strip("/") / "index.html" if path != "/" else WEB / "index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)


def main() -> int:
    (WEB / "js" / "core" / "site.js").write_text(
        "// GENERATED by web/tools/build_pages.py from web/site.json. Do not edit.\n"
        f"export const SITE = {json.dumps({k: v for k, v in SITE.items() if not k.startswith('$')}, indent=2)};\n"
        "export default SITE;\n"
    )
    css_hash = bundle_css()
    boot = boot_script()
    comps = components()
    (WEB / "components" / "index.json").write_text(json.dumps(comps, indent=2) + "\n")

    importmap = json.dumps({"imports": {"three": "/vendor/three/three.module.min.js", "three/addons/": "/vendor/three/addons/"}})
    urls = []
    for r in ROUTES["pages"]:
        attrs = f' data-variant="{esc(r["variant"])}"' if r.get("variant") else ""
        write(r["path"], page(path=r["path"], title=r["title"], description=r["description"], module=r["module"],
                              og=r["og"], body_attrs=attrs, shell=r.get("shell", ""), css_hash=css_hash, boot=boot,
                              importmap=importmap if r["path"] == "/3d/" else ""))
        urls.append(r["path"])
    for c in comps:
        path = f"/embed/{c['name']}/"
        write(path, page(path=path, title=f"{c['title']} · {SITE['name']} embed", description=c["summary"],
                         module="js/pages/embed.js", og=f"embed-{c['name']}", body_class="nc-embed",
                         body_attrs=f' data-component="{esc(c["name"])}"', css_hash=css_hash, boot=boot, embed=True,
                         also=f"components/{c['name']}/{c['name']}.js"))
        urls.append(path)

    origin = SITE["origin"].rstrip("/")
    (WEB / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{origin}{u}</loc></url>\n" for u in urls if not u.startswith("/embed/"))
        + "</urlset>\n"
    )
    (WEB / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {origin}/sitemap.xml\n")
    print(f"pages: {len(ROUTES['pages'])} pages, {len(comps)} embeds, css {css_hash}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
